// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_destroyer = "CgkIy87y08kWEAIQBg"; // <GPGSID>
        public const string achievement_recruit = "CgkIy87y08kWEAIQAg"; // <GPGSID>
        public const string achievement_hunter = "CgkIy87y08kWEAIQBA"; // <GPGSID>
        public const string achievement_warrior = "CgkIy87y08kWEAIQAw"; // <GPGSID>
        public const string achievement_kamikaze = "CgkIy87y08kWEAIQCw"; // <GPGSID>
        public const string achievement_stewardess = "CgkIy87y08kWEAIQBw"; // <GPGSID>
        public const string achievement_novice_pilot = "CgkIy87y08kWEAIQCQ"; // <GPGSID>
        public const string achievement_fighter_pilot = "CgkIy87y08kWEAIQCg"; // <GPGSID>
        public const string achievement_master_hunter = "CgkIy87y08kWEAIQBQ"; // <GPGSID>
        public const string achievement_second_pilot = "CgkIy87y08kWEAIQCA"; // <GPGSID>

}

